### PR TITLE
Improvements for Text-to-Speech scripts

### PR DESCRIPTION
**Pull request by DaveOHenry**
- The scripts now work on Linux and Windows
- Curl is not needed any more. 
- Improved the ffmpeg call. It uses the concat demuxer (stream copy) now instead of the protocol (file copy). This fixes a problem that the merged mp3s were cut off at the beginning in some cases / on some DFPlayers.
- The mp3 metadata is copied from the source to the destination file

### CODE REVIEW

**Comment by seisfeld** [comment]
Thanks for this. Question: Did you test all available speech systems, especially Amazon Polly? You explicitly mention only Google...

**Comment by DaveOHenry** [comment]
Unfortunately not. I only tested Google TTS (Ubuntu 18.04 and Windows 10).

**Comment by seisfeld** [comment]
I see, I gonna test Polly then. The local one (say on MacOS X) should be unaffected.

**Comment by seisfeld** [comment]
Does your change break compatibility with python 2? It does not even start anymore:

```
$ tools/create_audio_messages.py 
Traceback (most recent call last):
  File "tools/create_audio_messages.py", line 6, in <module>
    import argparse, os, re, shutil, sys, text_to_speech
  File "/Users/stephan/Downloads/DaveOHenry/TonUINO/tools/text_to_speech.py", line 6, in <module>
    import argparse, base64, json, os, subprocess, sys, urllib.request
ImportError: No module named request
```

```
10:52 $ python --version
Python 2.7.17
```

It works fine with Python 3 (just tested with Amazon Polly).

**Comment by DaveOHenry** [comment]
I see. The module is not available here. Did it work in Python 2 before? The original code was written in Python 3. I think I tried it in Python 2 when I first discovered this project, but it did not work. So I just used Python 3 instead ever since.

**Comment by seisfeld** [comment]
Yes, what is currently in the Repo does work with Python 2.

Python 3 requirement is not a dealbreaker though. We could update the documentation so that you explicitly need to run `python3 tools/<scriptname>`. But before, you could run just `tools/<scriptname>` since the script includes the `#!/usr/bin/python` - but what if that points to Python 2. There might be users who are not able to deal with that issue.

Any suggestions how we could make this better?

**Comment by DaveOHenry** [comment]
That is a very good point. I tried to catch the import error and change the import for Python 2, but the urllib modules are not compatible between Python 2 and 3. Some essential functions are missing in the old one and trying to work around these issues would make the code more complex than necessary.

I think that nobody should use Python 2 or write compatible code any more. It should only be used when dealing with complex legacy code that was written ages ago.
However, the problem is that some OS distributions still ship with Python 2 as default. The best way to deal with this seems to be changing the shebang line in all scripts to:

`#!/usr/bin/env python3`

This form is the most compatible one as far as I can tell and has a special meaning: It searches for a "python3" executable in the environment and works on Linux as well Windows systems.

**Comment by seisfeld** [comment]
> The best way to deal with this seems to be changing the shebang line in all scripts to:
> 
> #!/usr/bin/env python3
> 
> This form is the most compatible one as far as I can tell and has a special meaning: It searches for a "python3" executable in the environment and works on Linux as well Windows systems.

Works on Mac OS X as well, after Python 3 is installed via Homebrew. So my suggestion: Please amend the scripts to include the above change. I will then merge it and also push a change to the documentation that Python 3 is a requirement now and how to get it.

**Comment by seisfeld** [comment]
Good idea with the warning. Please amend the message to:

> WARNING: It looks like you are using an old version of Python. Please use Python 3 if you intend to use Google Text to Speech or Amazon Polly.

This also fixes a typo.

**Comment by DaveOHenry** [comment]
Amazon Polly should just work. The code uses the aws command line tools via the python subprocess module. No custom http api calls.

**Comment by seisfeld** [comment]
Okay. Great. In which case:

> WARNING: It looks like you are using an old version of Python. Please use Python 3 if you intend to use Google Text to Speech.

Fixes a typo. After that we are good to go I think. Exciting morning. ;)

**Pull request merged**
