### PR TITLE
adds TM1637 support for displaying of the album and track numbers

### PR DESCRIPTION
**Pull request by FxAlex**
show the album number during setup and the track number during playback

### CODE REVIEW

**Comment by FxAlex** [comment]
feel free to extend the display features.
Helpful page: https://www.dcode.fr/7-segment-display#1

**Comment by seisfeld** [comment]
Thanks for the PR. Unfortunately I currently don’t have such a display at hand. I will look at this once I have one.

**Comment by FxAlex** [comment]
why?

**Comment by seisfeld** [comment]
I'm sorry. I don't have time to work on this nor do I have such display to test. This is by no means that your idea is bad or anything. It's entirely on my end.

**Comment by FxAlex** [comment]
maybe someone else could test it?

**Pull request closed without merging**
